"""
Voyage AI embeddings tool for the Contract Deviation Detection Agent.

Turns clause text into embedding vectors and compares them with cosine
similarity. Requests are batched (one API call for many texts) and results are
cached in memory, because the free Voyage tier without a payment method is
limited to 3 requests and 10,000 tokens per minute.
"""

import json
import logging
import os
import time
from pathlib import Path

import numpy as np
import voyageai
from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[1]
load_dotenv(dotenv_path=PROJECT_ROOT / ".env")

DEFAULT_MODEL = "voyage-3.5"
BATCH_SIZE = 128
MAX_RETRIES = 3
RATE_LIMIT_WAIT_SECONDS = 21

logger = logging.getLogger(__name__)

_cache = {}
_stats = {"api_calls": 0, "cache_hits": 0, "tokens": 0}
_client = None


class EmbeddingError(RuntimeError):
    """Raised when embeddings cannot be generated by Voyage AI."""


def _model_name():
    """
    Return the Voyage model configured for this project.

    Returns:
        str: The value of VOYAGE_MODEL, or the default model if it is not set.
    """
    return os.environ.get("VOYAGE_MODEL", DEFAULT_MODEL)


def _get_client():
    """
    Create the Voyage client once and reuse it.

    Returns:
        voyageai.Client: An authenticated Voyage AI client.

    Raises:
        EmbeddingError: If VOYAGE_API_KEY is not set.
    """
    global _client
    if _client is None:
        api_key = os.environ.get("VOYAGE_API_KEY")
        if not api_key:
            raise EmbeddingError(
                "VOYAGE_API_KEY is not set. Add it to .env for local runs, or to "
                "the Streamlit Cloud secrets panel for the deployed app."
            )
        _client = voyageai.Client(api_key=api_key)
    return _client


def _is_rate_limit(error):
    """
    Decide whether an exception from Voyage is a rate-limit rejection.

    Args:
        error (Exception): The exception raised by the Voyage client.

    Returns:
        bool: True if the error indicates HTTP 429 / rate limiting.
    """
    return "ratelimit" in type(error).__name__.lower() or "429" in str(error)


def _embed_batch(texts, input_type):
    """
    Send one batch of texts to Voyage AI, retrying on rate-limit errors.

    Args:
        texts (list[str]): The texts to embed in a single request.
        input_type (str): Voyage input type, e.g. "document".

    Returns:
        list[list[float]]: One embedding per input text, in order.

    Raises:
        EmbeddingError: If the request fails for any reason other than a
            rate limit, or still fails after MAX_RETRIES attempts.
    """
    client = _get_client()
    model = _model_name()
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            result = client.embed(texts, model=model, input_type=input_type)
            _stats["api_calls"] += 1
            _stats["tokens"] += result.total_tokens
            return result.embeddings
        except Exception as error:
            if _is_rate_limit(error) and attempt < MAX_RETRIES:
                logger.warning(
                    "Voyage rate limit reached - waiting %ss before retry %s of %s",
                    RATE_LIMIT_WAIT_SECONDS, attempt + 1, MAX_RETRIES,
                )
                time.sleep(RATE_LIMIT_WAIT_SECONDS)
                continue
            if "auth" in type(error).__name__.lower():
                raise EmbeddingError(
                    "Voyage AI rejected the API key. Check VOYAGE_API_KEY in .env "
                    "matches an active key at dashboard.voyageai.com."
                ) from error
            raise EmbeddingError(
                f"Voyage AI request failed for model '{model}' with {len(texts)} "
                f"text(s). Check your network connection, that the model name is "
                f"valid, and your usage on the Voyage dashboard. "
                f"Underlying error: {error}"
            ) from error
    raise EmbeddingError(
        f"Voyage AI rate limit persisted after {MAX_RETRIES} attempts. Wait one "
        f"minute and try again, or add a payment method to raise the limit."
    )


def generate_embeddings(texts, input_type="document"):
    """
    Return embeddings for many texts, calling Voyage only for uncached ones.

    Args:
        texts (list[str]): The texts to embed.
        input_type (str): Voyage input type. Defaults to "document".

    Returns:
        list[list[float]]: One embedding per input text, in the same order.

    Raises:
        ValueError: If any text is empty or not a string.
        EmbeddingError: If the Voyage request fails.
    """
    model = _model_name()
    missing = []
    seen = set()
    for text in texts:
        if not isinstance(text, str) or not text.strip():
            raise ValueError("Cannot embed an empty or non-string text.")
        key = (model, input_type, text)
        if key in _cache:
            _stats["cache_hits"] += 1
        elif text not in seen:
            seen.add(text)
            missing.append(text)

    for start in range(0, len(missing), BATCH_SIZE):
        batch = missing[start:start + BATCH_SIZE]
        for text, embedding in zip(batch, _embed_batch(batch, input_type)):
            _cache[(model, input_type, text)] = embedding

    return [_cache[(model, input_type, text)] for text in texts]


def generate_embedding(text, input_type="document"):
    """
    Return the embedding for a single text.

    Args:
        text (str): The text to embed.
        input_type (str): Voyage input type. Defaults to "document".

    Returns:
        list[float]: The embedding vector.
    """
    return generate_embeddings([text], input_type=input_type)[0]


def compute_similarity(vector_a, vector_b):
    """
    Cosine similarity between two embeddings, clipped to the range 0.0-1.0.

    Args:
        vector_a (list[float]): The first embedding.
        vector_b (list[float]): The second embedding.

    Returns:
        float: 1.0 for identical direction, 0.0 for unrelated or opposite.

    Raises:
        ValueError: If the vectors differ in length or either has zero length.
    """
    a = np.asarray(vector_a, dtype=float)
    b = np.asarray(vector_b, dtype=float)
    if a.shape != b.shape:
        raise ValueError(f"Cannot compare embeddings of lengths {a.size} and {b.size}.")
    norm_product = np.linalg.norm(a) * np.linalg.norm(b)
    if norm_product == 0:
        raise ValueError("Cannot compute similarity with a zero-length embedding.")
    return float(np.clip(np.dot(a, b) / norm_product, 0.0, 1.0))


def get_stats():
    """
    Report API usage and cache behaviour since the last clear_cache().

    Returns:
        dict: Counts of API calls, cache hits and tokens used.
    """
    return dict(_stats)


def clear_cache():
    """Empty the embedding cache and reset the usage counters."""
    _cache.clear()
    for key in _stats:
        _stats[key] = 0


def main():
    """Self-test: embed the approved library twice and show the cache working."""
    logging.basicConfig(level=os.environ.get("LOG_LEVEL", "INFO"))
    library_dir = PROJECT_ROOT / "data" / "approved_clause_library"
    texts = []
    for path in sorted(library_dir.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        texts.extend(clause["text"] for clause in data["approved_clauses"])

    first = generate_embeddings(texts)
    after_first = get_stats()
    generate_embeddings(texts)
    after_second = get_stats()

    print(f"Model            : {_model_name()}")
    print(f"Clauses embedded : {len(first)} | dimensions: {len(first[0])} | "
          f"values are floats: {isinstance(first[0][0], float)}")
    print(f"First pass       : {after_first['api_calls']} API call(s), "
          f"{after_first['tokens']} tokens")
    print(f"Second pass      : {after_second['api_calls'] - after_first['api_calls']} "
          f"new API call(s), {after_second['cache_hits']} cache hits")
    print(f"Self-similarity  : {compute_similarity(first[0], first[0]):.3f}")
    print(f"Cross-category   : {compute_similarity(first[0], first[-1]):.3f} "
          f"(first liability clause vs last warranty clause)")


if __name__ == "__main__":
    main()